let productos = [
  {
    ID_Producto: 1,
    NombreProducto: "Teclado",
    DescripcionProducto: "texto texto texto texto",
    PrecioProducto: 456,
    sctokProducto: 20,
    imagenProducto: "https://i.pravatar.cc/200?u=1",
    descuentoProducto: 12.5,
    ID_Calificacion: 1,
    ID_Categoria: 6,
    estado: false,
    ID_TipoEnvio: 1,
  },
  {
    ID_Producto: 2,
    NombreProducto: "Teclado",
    DescripcionProducto: "texto texto texto texto",
    PrecioProducto: 456,
    sctokProducto: 20,
    imagenProducto: "https://i.pravatar.cc/200?u=2",
    descuentoProducto: 12.5,
    ID_Calificacion: 1,
    ID_Categoria: 6,
    estado: true,
    ID_TipoEnvio: 1,
  },
  {
    ID_Producto: 3,
    NombreProducto: "Teclado",
    DescripcionProducto: "texto texto texto texto",
    PrecioProducto: 456,
    sctokProducto: 20,
    imagenProducto: "https://i.pravatar.cc/200?u=3",
    descuentoProducto: 12.5,
    ID_Calificacion: 1,
    ID_Categoria: 6,
    estado: true,
    ID_TipoEnvio: 1,
  },
  {
    ID_Producto: 4,
    NombreProducto: "Teclado",
    DescripcionProducto: "texto texto texto texto",
    PrecioProducto: 456,
    sctokProducto: 20,
    imagenProducto: "https://i.pravatar.cc/200?u=4",
    descuentoProducto: 12.5,
    ID_Calificacion: 1,
    ID_Categoria: 6,
    estado: true,
    ID_TipoEnvio: 1,
  },
  {
    ID_Producto: 5,
    NombreProducto: "Teclado",
    DescripcionProducto: "texto texto texto texto",
    PrecioProducto: 456,
    sctokProducto: 20,
    imagenProducto: "https://i.pravatar.cc/200?u=5",
    descuentoProducto: 12.5,
    ID_Calificacion: 1,
    ID_Categoria: 6,
    estado: true,
    ID_TipoEnvio: 1,
  },
  {
    ID_Producto: 6,
    NombreProducto: "Monitor",
    DescripcionProducto: "texto texto texto texto",
    PrecioProducto: 456,
    sctokProducto: 20,
    imagenProducto: "https://i.pravatar.cc/200?u=6",
    descuentoProducto: 12.5,
    ID_Calificacion: 1,
    ID_Categoria: 6,
    estado: true,
    ID_TipoEnvio: 1,
  }
];

let productosCart = []
