let productos = [
  {
    ID_Producto: 1,
    NombreProducto: "Teclado",
    DescripcionProducto: "Teclado Basico",
    PrecioProducto: 50,
    sctokProducto: 6,
    imagenProducto: "https://i.pravatar.cc/200?u=1",
    descuentoProducto: 12.5,
    ID_Calificacion: 1,
    ID_Categoria: 2,
    estado: false,
    ID_TipoEnvio: 1,
  },
  {
    ID_Producto: 2,
    NombreProducto: "Mouse",
    DescripcionProducto: "Mouse Gamer",
    PrecioProducto: 150,
    sctokProducto: 20,
    imagenProducto: "https://i.pravatar.cc/200?u=2",
    descuentoProducto: 12.5,
    ID_Calificacion: 1,
    ID_Categoria: 1,
    estado: true,
    ID_TipoEnvio: 1,
  },
  {
    ID_Producto: 3,
    NombreProducto: "Monitor",
    DescripcionProducto: "Monitor basico",
    PrecioProducto: 1200,
    sctokProducto: 5,
    imagenProducto: "https://i.pravatar.cc/200?u=3",
    descuentoProducto: 12.5,
    ID_Calificacion: 1,
    ID_Categoria: 2,
    estado: true,
    ID_TipoEnvio: 1,
  },
  {
    ID_Producto: 4,
    NombreProducto: "Case Gamer",
    DescripcionProducto: "Case Gamer Alienware",
    PrecioProducto: 1500,
    sctokProducto: 10,
    imagenProducto: "https://i.pravatar.cc/200?u=4",
    descuentoProducto: 12.5,
    ID_Calificacion: 1,
    ID_Categoria: 1,
    estado: true,
    ID_TipoEnvio: 1,
  },
  {
    ID_Producto: 5,
    NombreProducto: "Microfono",
    DescripcionProducto: "Microfono Gamer",
    PrecioProducto: 456,
    sctokProducto: 20,
    imagenProducto: "https://i.pravatar.cc/200?u=5",
    descuentoProducto: 12.5,
    ID_Calificacion: 1,
    ID_Categoria: 1,
    estado: true,
    ID_TipoEnvio: 1,
  },
  {
    ID_Producto: 6,
    NombreProducto: "Laptop Gamer",
    DescripcionProducto: "Laptop Gamer Lenovo",
    PrecioProducto: 5600,
    sctokProducto: 100,
    imagenProducto: "https://i.pravatar.cc/200?u=6",
    descuentoProducto: 12.5,
    ID_Calificacion: 1,
    ID_Categoria: 1,
    estado: true,
    ID_TipoEnvio: 1,
  },
];

let productosCart = [];

let categorias = [
  { ID_Categoria: 1, NombreCategoria: "Gamer" },
  { ID_Categoria: 2, NombreCategoria: "Oficina" },
  { ID_Categoria: 3, NombreCategoria: "Comercial" },
  { ID_Categoria: 4, NombreCategoria: "Colegio" },
  { ID_Categoria: 5, NombreCategoria: "Otro Basico" },
  { ID_Categoria: 6, NombreCategoria: "Otro Gamer" },
];
let clasificacion = [];
let tipoEnvio = [];
